#!/usr/bin/env python3
"""Write ``src/dns_updater/_build_metadata.py`` before ``uv build``.

Environment variables:

* ``CLOUDFLARE_DNS_UPDATER_EMBED_VERSION`` — package version (for example ``0.1.0``).
* ``CLOUDFLARE_DNS_UPDATER_EMBED_COMMIT`` — full or short git SHA (first 12 hex chars kept).
"""

from __future__ import annotations

import os
from pathlib import Path


def _normalize_embedded_commit(raw: str) -> str:
    token = raw.strip()
    if not token:
        return ""
    if len(token) > 12:
        return token[:12]
    return token


def _write_metadata_file(repo_root: Path, version: str, commit: str) -> None:
    path = repo_root / "src" / "dns_updater" / "_build_metadata.py"
    body = f'''"""Autogenerated by scripts/embed_build_metadata.py — do not hand-edit."""

from __future__ import annotations

EMBEDDED_COMMIT: str = {commit!r}
EMBEDDED_VERSION: str = {version!r}
'''
    path.write_text(body, encoding="utf-8")


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    version = os.environ.get("CLOUDFLARE_DNS_UPDATER_EMBED_VERSION", "").strip()
    commit = _normalize_embedded_commit(os.environ.get("CLOUDFLARE_DNS_UPDATER_EMBED_COMMIT", ""))
    _write_metadata_file(repo_root, version, commit)


if __name__ == "__main__":
    main()
